### ISSUE TITLE
Systemctl in Ubuntu 14.04

### ISSUE THREAD

**Issue by rbshadow** [joanbono/Snorter#12]
**systemctl command not found.**
So upstart service isn't start.

**Comment by rbshadow** [comment]
![screenshot from 2017-06-05 14 40 27](https://cloud.githubusercontent.com/assets/12114842/26776900/02472c50-49fd-11e7-80a3-10578e53c2c5.png)

**Comment by rbshadow** [comment]
![screenshot from 2017-06-05 14 44 27](https://cloud.githubusercontent.com/assets/12114842/26777029/81c365f2-49fd-11e7-9841-ea1e2fffc915.png)

**Comment by joanbono** [comment]
Hi @rbshadow .

Ubuntu started using `systemd` in 15.04. Before 15.04, Ubuntu uses `upstart`. 

So, you have two options:

+ Update your Ubuntu to 15.04 or above.
+ Create the service manually and then do: `update-rc.d snort enable`.

I won't fix this at the moment, because it's a problem just for this release and I don't have time at the moment.

If you want to fix the problem and then open a pull request, you're welcome.

Kind regards

**Comment by joanbono** [comment]
Hi @rbshadow I'm going to close this issue.

If you want to work in the Snorter adapted to Ubuntu 14.04, please let me know and I'll help you, or reopen this issue.

Regards

**Comment by rbshadow** [comment]
I fixed that issue for Ubuntu 14.04. Thank you.

**Comment by joanbono** [comment]
Awesome work, @rbshadow , I'll add your name in the README, in the **Agreements**.

Thanks for contributing.

**Comment by rbshadow** [comment]
Welcome bro, @joanbono . Thank you for your excellent work.
