### ISSUE TITLE
Problem with sudo in Debian

### ISSUE THREAD

**Issue by andreumont** [joanbono/Snorter#18]
Hello!

When you try to install **snorter** packages on Debian systems, there appear some errors because _sudo_ isn't installed in the OS by default.

Maybe you can change the script to let people install snorter without the requirement to have sudo installed.

Many thanks for your apport to comunity. Good job bro!

**Comment by joanbono** [comment]
I'll check this, but I think is preferrable to install `sudo` and add the user to the `sudoers`, because all the other **Debian-based** distros come with `sudo` installed by default. 

I'll check this. 

Good catch! 

Thanks!! 😄

**Comment by HarriL** [comment]
For security reasons you should never add a sudo inside scripts! 
1. inside in a script user/installed does not know that there is root priviledge used because it is hidden
2. during a long execution the sudo may ask password and silently fail
So it is better to run the installation script with sudo than add sudo inside.

**Comment by joanbono** [comment]
Thanks @HarriL, yes, you're rigth. I'll keep an eye on this when I finish my holidays.

Please stay tuned, I may need some advice on this.

Thanks a lot :D
